// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crypto_api.Data;

#nullable disable

namespace crypto_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221005153719_crypto")]
    partial class crypto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("crypto_api.Models.Crypto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Current_price")
                        .HasColumnType("float");

                    b.Property<double>("High_24h")
                        .HasColumnType("float");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_update")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Low_24h")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total_volume")
                        .HasColumnType("float");

                    b.Property<double>("ath")
                        .HasColumnType("float");

                    b.Property<double>("ath_change_percentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("ath_date")
                        .HasColumnType("datetime2");

                    b.Property<double>("fully_diluted_valuation")
                        .HasColumnType("float");

                    b.Property<double>("market_cap")
                        .HasColumnType("float");

                    b.Property<double>("market_cap_change_24h")
                        .HasColumnType("float");

                    b.Property<double>("market_cap_change_percentage_24h")
                        .HasColumnType("float");

                    b.Property<double>("market_cap_rank")
                        .HasColumnType("float");

                    b.Property<double>("max_supply")
                        .HasColumnType("float");

                    b.Property<double>("price_change_24h")
                        .HasColumnType("float");

                    b.Property<double>("price_change_percentage_24h")
                        .HasColumnType("float");

                    b.Property<double>("roi")
                        .HasColumnType("float");

                    b.Property<double>("total_supply")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Cryptos");
                });

            modelBuilder.Entity("crypto_api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("crypto_api.Models.WatchList", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WatchList");
                });
#pragma warning restore 612, 618
        }
    }
}
